version: '3'

services:
  seventiny.cloud.multitenantplatform.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  seventiny.cloud.multitenantplatform.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  seventiny.cloud.multitenantplatform.dataapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
